### ISSUE TITLE
Serial2 setup

### ISSUE THREAD

**Issue by mackelec** [dalathegreat/BYD-Battery-Emulator-For-Gen24#104]
https://github.com/dalathegreat/BYD-Battery-Emulator-For-Gen24/blob/0bfb757dffda995c507f8ee7bad2773715c2ed87/Software/Software.ino#L230

should be

Serial2.begin(9600, SERIAL_8N1, RS485_RX_PIN, RS485_TX_PIN);

**Comment by dalathegreat** [comment]
Working on this in the [feature/double-lilygo](https://github.com/dalathegreat/BYD-Battery-Emulator-For-Gen24/tree/feature/double-lilygo) branch!
