### ISSUE TITLE
Use whole Leaf as a battery for Hybrid Solar inverter?

### ISSUE THREAD

**Issue by fototakas** [dalathegreat/BYD-Battery-Emulator-For-Gen24#11]
Hello Dala,
Thanks for sharing another nice project.
What do you think is it possible to use same approach and connect Leaf using CHAdeMO to Hybrid inverter as HV battery? in theory we would be able to charge Leaf with DC from panels, and use car for emergency backup. I must admit, that most expensive part will be the CHAdeMO plug :)

**Comment by dalathegreat** [comment]
Hi @fototakas 

See this reply here: https://github.com/dalathegreat/BYD-Battery-Emulator-For-Gen24/issues/7#issuecomment-1493375939

Closing this as duplicate

**Comment by fototakas** [comment]
@dalathegreat Found Chademo plug with cable for the good price, still 2 available:
https://www.ebay.com/itm/235021221143
