### ISSUE TITLE
Sourcing a Nissan Leaf 62 kWh battery in(to) Europe ?

### ISSUE THREAD

**Issue by pgodefroy** [dalathegreat/BYD-Battery-Emulator-For-Gen24#110]
Can anyone suggest the best way to source a Nissan Leaf 62 kWh battery in(to) Europe ?
Anyone experience importing new replacement battery packs them from China ?
e.g.
https://www.augenergy.com/index.php?route=product/product&path=61&product_id=79

**Comment by dalathegreat** [comment]
@pgodefroy This is not the correct place for discussing this. This is the bug report section for the Battery-Emulator

Try the discussion forum https://secondlifestorage.com/index.php
I buy from Norway, for instance GBD https://gbd.no/utvalgte-deler/batteripakke-elbil/
