### ISSUE TITLE
Fronius Gen24 stops working at -10°C

### ISSUE THREAD

**Issue by dalathegreat** [dalathegreat/BYD-Battery-Emulator-For-Gen24#111]
### Problem description
The Fronius Gen24 (and other Fronius inverters also affected), will stop charge/discharge if the battery gets colder than -10°C. This is due to the original battery pack (BYD HVM), is a lithium iron phosphate battery, that cannot be charged in cold weather. When using NCM/LMO/NCA batteries, this is not a problem, since these chemistries are OK for outdoor cold use.

![bild](https://github.com/dalathegreat/BYD-Battery-Emulator-For-Gen24/assets/26695010/c3f62291-1dd9-4528-bbef-b8c3b18fe43f)

### Suggested solution
We should freeze (pun intended), the values between -10 to -20°C, and fool the inverter that the battery is warmer than it actually is. Most EV packs have built in heaters, for instance the LEAF pack will turn the heat on at -17°C. This way we can still have a too cold shutdown at -20, which is a far more reasonable limit than -10. Incase you actually see -20°C with a LEAF pack, it means your heater has failed to kick in (and you should look into why)

**Comment by lenvm** [comment]
@dalathegreat, this issue should be fixed in #112. Shall we close this issue?
