### ISSUE TITLE
Giv energy 

### ISSUE THREAD

**Issue by biftabravo** [dalathegreat/BYD-Battery-Emulator-For-Gen24#114]
Any chance of getting the giv energy inverters added? 

I have a gen 2 (GIV-HY3.6-G2) version and would like a leaf battery adding to it.

 This project is amazing!

**Comment by dalathegreat** [comment]
@biftabravo The GIV inverters only take 48V batteries. This entire Battery-Emulator project focuses on safe re-use of 300-400V batteries, so the GIV inverters are not suitable at all for this.
![bild](https://github.com/dalathegreat/BYD-Battery-Emulator-For-Gen24/assets/26695010/8aac8b5c-a502-4507-8af8-82dc52b74870)

I suggest looking for another inverter!

**Comment by biftabravo** [comment]
Thought as much! Guess I bought the wrong equipment. 

Thanks for the reply
