### ISSUE TITLE
Tesla battery power wrong value on the webpage

### ISSUE THREAD

**Issue by MarkoBolt** [dalathegreat/BYD-Battery-Emulator-For-Gen24#118]
Battery power has the wrong value shown on the webpage. 

<img width="277" alt="Screenshot 2024-01-02 at 17 41 30" src="https://github.com/dalathegreat/BYD-Battery-Emulator-For-Gen24/assets/11732640/1dcd2c60-83e7-4fc4-be78-f262ad097cff">

Could the following line cause an overflow?

https://github.com/dalathegreat/BYD-Battery-Emulator-For-Gen24/blob/430da0e0bd7f35e1cdde4469e814cecd5ef30641/Software/src/battery/TESLA-MODEL-3-BATTERY.cpp#L205C3-L205C68

Suggestion: 

`stat_batt_power = ( (volts/10) * amps); `

**Comment by dalathegreat** [comment]
Nice find @MarkoBolt , I pushed an attempted fix to this branch: https://github.com/dalathegreat/BYD-Battery-Emulator-For-Gen24/compare/main...bugfix/tesla-power

Wanna test it? :)

**Comment by MarkoBolt** [comment]
Tested it, dot not work ok yet.

Tested with the following line ant then it seems to be ok. 

`power = ((volts/10) * amps); `

Value is too large for the variable power, causing an overflow in the variable power. Next to that it should be 10 times less, so the divide by 10 helps in this case, so it is scaled ok.

**Comment by dalathegreat** [comment]
@MarkoBolt Thanks! Fixed in https://github.com/dalathegreat/BYD-Battery-Emulator-For-Gen24/pull/119/commits/6b06132607e9e00539ac3b27a95d9786567132ab
