### ISSUE TITLE
Disable WIFI AP

### ISSUE THREAD

**Issue by MarkoBolt** [dalathegreat/BYD-Battery-Emulator-For-Gen24#122]
Can we make an option to disable the standard on AP in the webserver?

I have tested the following code and that seem to work:

`  #ifdef WEBSERVER_AP
    WiFi.mode(WIFI_AP_STA);  // Simultaneous WiFi Access Point and WiFi STAtion
    init_WiFi_AP(); 
  #endif
  #ifdef WEBSERVER_STA
    WiFi.mode(WIFI_STA);  // Simultaneous WiFi Access Point and WiFi STAtion
  #endif`

In "webserver.ccp" at line: 
https://github.com/dalathegreat/BYD-Battery-Emulator-For-Gen24/blob/8ff6209617a3f38cbfa252ecd06b2f5a0a9e945e/Software/src/devboard/webserver/webserver.cpp#L46C1-L48C33

And added these lines below in "USER_SETTINGS.h "#define WEBSERVER  //Enable this line to enable WiFi, and to run the webserver" :
`#define WEBSERVER_STA //Enable station that connects to WIFI
//#define WEBSERVER_AP // Enable accesspoint when WEBSERVER is enabled.`

**Comment by dalathegreat** [comment]
@MarkoBolt Great idea! I implemented a way to disable the AP in this Pull Request: https://github.com/dalathegreat/BYD-Battery-Emulator-For-Gen24/pull/123
