### ISSUE TITLE
Type conflict bms_status and bms_char_dis_status

### ISSUE THREAD

**Issue by davidhgriffiths** [dalathegreat/BYD-Battery-Emulator-For-Gen24#129]
webserver.h defines  bms_status and bms_char_dis_status as uint16_t but SOLAX-CAN.h defines them as uint8_t.  Changing the type in webserver.h to uint8_t allows compilation for SOLAX-CAN but will not doubt break compilation for some other inverters

**Comment by dalathegreat** [comment]
@davidhgriffiths Thanks for spotting that, fixed in PR https://github.com/dalathegreat/BYD-Battery-Emulator-For-Gen24/pull/130
