### ISSUE TITLE
Weird characters in Serial Monitor

### ISSUE THREAD

**Issue by Jhonyboy72** [dalathegreat/BYD-Battery-Emulator-For-Gen24#134]
First of All: Thanks for the great, great work.

today i uploaded the Software to LilyGo-Board. Everthing just fine. 
But wenn ik open the Serial Monitor i only see weird characters.
Anyone else had this problem before and knows how to solve it?

Thanks in advance

![wc](https://github.com/dalathegreat/BYD-Battery-Emulator-For-Gen24/assets/109593821/a5f3d1ee-24d0-49ae-9c49-5a7f78e9eae3)

**Comment by LevinSwe** [comment]
Hi,
Change your baudrate to 115200 👍
Regards
![prscr01](https://github.com/dalathegreat/BYD-Battery-Emulator-For-Gen24/assets/18295343/ef7e6fcb-4440-4801-8a6c-7a7879e0b441)

**Comment by Jhonyboy72** [comment]
Works just fine now! Thank you very much!
