### ISSUE TITLE
Battery compability list

### ISSUE THREAD

**Issue by bruvv** [dalathegreat/BYD-Battery-Emulator-For-Gen24#16]
In the readme you write: "You will also need a complete EV battery. See the battery compability list on which are supported." where is this list?

**Comment by AlexJamesHaines** [comment]
This is a valid question and I haven't spotted it on quick inspection of the code. I'd propose that early 30kwh leafs are a good choice but it would be nice to have the list somewhere 👍

**Comment by bruvv** [comment]
@AlexJamesHaines I think tesla battery is also supported: https://github.com/dalathegreat/BYD-Battery-Emulator-For-Gen24/blob/main/Images/Tesla_X098.png

**Comment by dalathegreat** [comment]
@bruvv and @AlexJamesHaines , see the Wiki section: https://github.com/dalathegreat/BYD-Battery-Emulator-For-Gen24/wiki#supported-batteries-list

**Comment by AlexJamesHaines** [comment]
Not sure how I missed that. Thanks 👍
