### ISSUE TITLE
Faulty CAN wiring can crash board

### ISSUE THREAD

**Issue by dalathegreat** [dalathegreat/BYD-Battery-Emulator-For-Gen24#27]
The CAN code is a bit strange on this board. If there is not someone alive on the CAN bus to ack the messages that the board sends, then the entire board will crash. The problem is that after the watchdog resets the board, the crash will continue to happen (since the code will try to send more CAN messages right away). After restoring the wires the board starts working again.

In proper CAN terminology, I believe this is called a BUS error state.

Steps to reproduce:
- Setup LilyGo board with a CAN device connected (I use Kvaser reader for testing)
- Setup terminating resistors to get 120Ohm in both ends (LilyGo has one built in)
- Start the program, for instance with "LEAF Battery" enabled.
- Observe how the green status LED on the board is blinking slowly, indicating that the board is alive
- Remove terminating resistor OR one CAN wire
- **Intended behaviour:** Board stays operational with pulsing green LED
- **Actual behaviour:** Board freezes up, the LED stays solid green on the board, indicating a crash

This isn't really a problem, since the Inverter that is connected should act accordingly and shut everything down in a CAN failure situation. But it would be very nice if the LilyGo could stay ON in this bus error state, since the board now can control contactors. In the event of CAN failure, after 60seconds the LilyGo enters faulted state, and in this state contactors are opened. So this bug is preventing this shutdown process from happening. Again, not a massive problem since the inverter will shut down the charge process.

Help wanted! :)

**Comment by rjsc** [comment]
> The miwagner arduino driver and Thomas Barthe's arduino ESP-32 CAN driver are significantly different than the current ESP-IDF CAN driver. They are *NOT* direct ports.

> The miwagner and Thomas Barth Arduino ESP32 CAN drivers have some big issues with queues, and it doesnt have any protection/safety with large multi-threaded/tasked programs. If you are trying to send CAN messages from several different areas of your multi-tasked code, it usually gets choked sooner or later....

> And the biggest issue of all is that it doesnt have the IRAM_ATTR directive, which would allow it to try to access random parts of flash/code at ANY time....this includes during an OTA update (which disables flash-cache). If you leave the miwagner/Thomas Barth Arduino ESP32 CAN driver running during an OTA update, it was guaranteed to crash the whole ESP32.

> The official ESP-IDF CAN driver doesnt have any of these issues, and is completely safe to use with any program, and have running at all times, including during an OTA update.

[https://esp32.com/viewtopic.php?t=12607](https://esp32.com/viewtopic.php?t=12607) 

Seems that the Arduino can stack indeed has problems and we need to use the official o e from the esp32 idf.

**Comment by dalathegreat** [comment]
Some good info here: https://github.com/sandeepmistry/arduino-CAN/pull/118

**Comment by dalathegreat** [comment]
Another repo with same problem: https://github.com/timurrrr/arduino-CAN/issues/2

**Comment by rjsc** [comment]
There is a pending pull request to add a timeout to the write operation but the repo owner didn't respond for over a year.
You can try to merge it privately and test.
[https://github.com/miwagner/ESP32-Arduino-CAN/pull/45](url)

**Comment by dalathegreat** [comment]
Pull request merged to main that prevents the crash 💪 ! Thanks @rjsc and Caboom! https://github.com/dalathegreat/BYD-Battery-Emulator-For-Gen24/pull/48
