### ISSUE TITLE
Feature request: Add compatibility for Tesla Model S/X battery

### ISSUE THREAD

**Issue by Emacee** [dalathegreat/BYD-Battery-Emulator-For-Gen24#41]
Given that there is quite a good availability of second hand Tesla Model S & X battery packs and there has been experimented quite a lot with the individual cells I was wondering if it it’s possible to make it compatible with this solution. 
I love the concept that a whole pack can stay intact with all the safety guards (E.g. pyro fuses) and am evaluating which packs to consider, this one is on top of my list.

**Comment by dalathegreat** [comment]
@Emacee Support for both Model 3 and Model Y is now stable ✅ in the latest 3.X.X software. Feel free to experiment with S/X incase you want, S/X from 2020 and newer should work with the same software!
