### ISSUE TITLE
Wrong array length

### ISSUE THREAD

**Issue by gp195** [dalathegreat/BYD-Battery-Emulator-For-Gen24#5]
Your definition is:  static uint16_t battery_data[23];
But you are using indices from 0..23!
Greetings from Austria, I want to build a BYD replacement with single cells...

**Comment by dalathegreat** [comment]
Thanks @gp195 , I really should have turned on compiler warnings in the Arduino IDE, it warns specifically about thatM

```
BYD-MODBUS-2-LEAF-CAN\BYD-MODBUS-2-LEAF-CAN.ino:209:17: error: array subscript 23 is above array bounds of 'uint16_t [23]' {aka 'short unsigned int [23]'} [-Werror=array-bounds]
  battery_data[23] = SOH;                                // Id.: p324 Value.: 9900 Scaled value.: 99% Comment.: SOH
```
I will issue a fix!
