### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by EnergibatteriMax** [dalathegreat/BYD-Battery-Emulator-For-Gen24#50]
I have many errors and warnings when compiling the software.
Am i doing something wrong.. 
Attaching part of the compile result file.
[Compile errors.txt](https://github.com/dalathegreat/BYD-Battery-Emulator-For-Gen24/files/12369632/Compile.errors.txt)

**Comment by dalathegreat** [comment]
Closing, turned out to be setting error :)
