### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by NiallDarwin** [dalathegreat/BYD-Battery-Emulator-For-Gen24#54]
[Flow chart](https://github.com/dalathegreat/BYD-Battery-Emulator-For-Gen24/blob/main/Images/BatteryControlWiring.png) for relay powering status indicates CAN messages to send at certain stages. Two issues:
1/ It is not made clear that 0x1D4 is the message with the signals
2/ There is a typo/lack of consistent terminology. Image states BTOFN, dbc file says BTONFN

https://github.com/dalathegreat/BYD-Battery-Emulator-For-Gen24/blob/main/Images/BatteryControlWiring.png

**Comment by dalathegreat** [comment]
Thanks, but that picture is from Nissan 😂 Not much sense in correcting it, it is just a FYI for those that need more nerdy info. And I don't think adding that this is in 1D4 is needed.
