### ISSUE TITLE
Operation of BYD emulator with SunGrow

### ISSUE THREAD

**Issue by mackelec** [dalathegreat/BYD-Battery-Emulator-For-Gen24#55]
I am seriously looking at buying a SunGrow SH10RS, single phase 10kW Hybrid, which are similar to other models you show as working.

I want to experiment with different batteries, different chemistries, different voltages, and so on.  I'm fine with coding and electronics, CAN bus, modbus, BMS and high volt batteries.  I have no experience with these Hybrid inverters and the "packaged batteries / powerwalls" like the BYD etc.

Question 1:

The Sungrow SH6.0RS has a Battery voltage range of 80 to 460V and a charge / discharge battery current of 30 Amp, and maximum power of 6600W.  using the BYD emulator, Does the SG inverter care what the voltage is, as long as I stay within 80-460V?  So is it responding only to SOC (and current maximums)?  I may want a 150V batttery, or use different chemistries which will have different curves etc, and so on.

In the case of the SH10RS, it supports up to 50Amps max, which is beyond  a single BYD HVM pack, will the inverter care if I set the emulator to 50 amps even though the std BYD HVM is max 30 Amps(if  I remember right)  ?

Question 2:

It is my understanding that the Fronius inverter and attached battery is Not isolated.  Would any know if the SunGrow SHx.0RS inverters are isolated from the battery?

**Comment by puffnfresh** [comment]
@mackelec did you find out about the SunGrow SH10RS?
